routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('/', 'PageController@index')->name('index');
Route::get('/website', function() {
    return redirect(config('app.externurl', config('app.url', '/')));
})->name('website');
Route::get('/support', 'PageController@support')->name('support');
//Route::get('/import', 'PageController@importdevices')->name('importdevices');

Auth::routes();

Route::resource('customers', 'CustomerController');

Route::resource('customers/{id}/passwords', 'PasswordController');
Route::resource('customers/{id}/documents', 'DocumentController');
Route::resource('customers/{id}/uploads', 'UploadController');
Route::get('/uploads/{id}/{apikey}', 'UploadController@direct')->name('direct');
Route::resource('customers/{id}/devices', 'DeviceController');
Route::resource('customers/{id}/devices/{devid}/upgradesets', 'UpgradeSetController');
Route::resource('customers/{id}/devices/{devid}/upgradesets/{upsetid}/upgrades', 'UpgradeController');
Route::resource('assets', 'AssetController');
Route::resource('apikeys', 'ApiKeyController');

Route::get('customers/{id}/report', 'CustomerController@report')->name('report');

resources/views/includes/messages.blade.php
@if(isset($errors) && count($errors) > 0)
    @foreach($errors->all() as $error)
        <div class="alert alert-danger">
            {{$error}}
        </div>
    @endforeach
@endif

@if(session('error'))
    <div class="alert alert-danger">
        {{session('error')}}
    </div>
@endif

@if(session('success'))
    <div class="alert alert-success">
        {{session('success')}}
    </div>
@endif

resources/views/includes/navbar.blade.php
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ route('index') }}">
                {{ config('app.name', 'Support CRS') }}
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
                <li><a href="{{route('website')}}">Main Website</a></li>
                <li><a href="{{route('support')}}">Support</a></li>
                @auth
                <li><a href="{{route('customers.index')}}">Customers</a></li>
                <li><a href="{{route('assets.index')}}">Assets</a></li>
                @endauth
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @guest
                    <li><a href="{{ route('login') }}">Login</a></li>
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            <li>
                                <a href="{{ route('apikeys.index') }}">
                                    Api Keys
                                </a>
                                <a href="{{ route('logout') }}"
                                    onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>